### ISSUE TITLE
Virtual event experience

### ISSUE THREAD

**Issue by bzz** [KTH/npr#3]
Hi,

could not find any mentions of this on the website, so I was wondering if the event will go be fully/partially virtual or are all the speakers and attendees are expected to come to Stockholm in Sep?

Thanks for organising it!

**Comment by fermadeiral** [comment]
Hi @bzz,

Thank you very much for contacting us. Unfortunately we will postpone the workshop because of the COVID-19 pandemic. The new date is to be decided. Hope you can join us!
